<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net9.0-windows</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <UseWPF>true</UseWPF>
  </PropertyGroup>

  <ItemGroup>
    <None Remove="uc\WhatsApp Image 2025-05-11 at 17.36.03.jpeg" />
  </ItemGroup>

  <ItemGroup>
    <Resource Include="uc\WhatsApp Image 2025-05-11 at 17.36.03.jpeg" />
  </ItemGroup>

</Project>
