//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18449
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Kronus.Client.Proxies.CoreService {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="CoreService.ICoreService")]
    public interface ICoreService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICoreService/DoWork", ReplyAction="http://tempuri.org/ICoreService/DoWorkResponse")]
        string DoWork();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICoreService/DoWork", ReplyAction="http://tempuri.org/ICoreService/DoWorkResponse")]
        System.Threading.Tasks.Task<string> DoWorkAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICoreService/GetMenu", ReplyAction="http://tempuri.org/ICoreService/GetMenuResponse")]
        System.Data.DataSet GetMenu(string vlDomainName);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICoreService/GetMenu", ReplyAction="http://tempuri.org/ICoreService/GetMenuResponse")]
        System.Threading.Tasks.Task<System.Data.DataSet> GetMenuAsync(string vlDomainName);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ICoreServiceChannel : Kronus.Client.Proxies.CoreService.ICoreService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class CoreServiceClient : System.ServiceModel.ClientBase<Kronus.Client.Proxies.CoreService.ICoreService>, Kronus.Client.Proxies.CoreService.ICoreService {
        
        public CoreServiceClient() {
        }
        
        public CoreServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public CoreServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public CoreServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public CoreServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public string DoWork() {
            return base.Channel.DoWork();
        }
        
        public System.Threading.Tasks.Task<string> DoWorkAsync() {
            return base.Channel.DoWorkAsync();
        }
        
        public System.Data.DataSet GetMenu(string vlDomainName) {
            return base.Channel.GetMenu(vlDomainName);
        }
        
        public System.Threading.Tasks.Task<System.Data.DataSet> GetMenuAsync(string vlDomainName) {
            return base.Channel.GetMenuAsync(vlDomainName);
        }
    }
}
